# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: itrp 0.1.5 ruby lib

Gem::Specification.new do |s|
  s.name = "itrp".freeze
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["vivekrajan".freeze]
  s.date = "2022-06-02"
  s.description = "iTRP is an extensible CLI app with tab completion for Network Security and Traffic Monitoring (NSM)".freeze
  s.email = "vivek@unleashnetworks.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "itrp.gemspec",
    "lib/cmd_base.rb",
    "lib/cmd_root.rb",
    "lib/handlers/agg_flow.rb",
    "lib/handlers/alert.rb",
    "lib/handlers/counter.rb",
    "lib/handlers/delete_alerts.rb",
    "lib/handlers/edges.rb",
    "lib/handlers/flow.rb",
    "lib/handlers/fts.rb",
    "lib/handlers/getlabel.rb",
    "lib/handlers/grep.rb",
    "lib/handlers/help.rb",
    "lib/handlers/keyspace.rb",
    "lib/handlers/list.rb",
    "lib/handlers/list_counters.rb",
    "lib/handlers/meters.rb",
    "lib/handlers/metric_summ.rb",
    "lib/handlers/options.rb",
    "lib/handlers/pcap.rb",
    "lib/handlers/probe.rb",
    "lib/handlers/query_alerts.rb",
    "lib/handlers/query_flow.rb",
    "lib/handlers/query_fts.rb",
    "lib/handlers/query_resource.rb",
    "lib/handlers/resource.rb",
    "lib/handlers/searchkey.rb",
    "lib/handlers/set.rb",
    "lib/handlers/setlabel.rb",
    "lib/handlers/timeslices.rb",
    "lib/handlers/toppers.rb",
    "lib/handlers/toptrend.rb",
    "lib/handlers/trackers.rb",
    "lib/handlers/traffic.rb",
    "lib/handlers/volume.rb",
    "lib/itrp.rb",
    "test/helper.rb",
    "test/test_itrp.rb"
  ]
  s.homepage = "http://github.com/vivekrajan/itrp".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.2.32".freeze
  s.summary = "iTRP - Command Line Interface to Trisul Network Analytics".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<trisulrp>.freeze, [">= 0"])
    s.add_runtime_dependency(%q<terminal-table>.freeze, [">= 0"])
    s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_development_dependency(%q<bundler>.freeze, [">= 0"])
    s.add_development_dependency(%q<juwelier>.freeze, [">= 0"])
    s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
  else
    s.add_dependency(%q<trisulrp>.freeze, [">= 0"])
    s.add_dependency(%q<terminal-table>.freeze, [">= 0"])
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<bundler>.freeze, [">= 0"])
    s.add_dependency(%q<juwelier>.freeze, [">= 0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

