# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: itrp 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "itrp"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["vivekrajan"]
  s.date = "2015-12-07"
  s.description = "iTRP is an extensible CLI app with tab completion for Network Security and Traffic Monitoring (NSM)"
  s.email = "vivek@unleashnetworks.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/cmd_base.rb",
    "lib/cmd_root.rb",
    "lib/handlers/alert.rb",
    "lib/handlers/counter.rb",
    "lib/handlers/delete_alerts.rb",
    "lib/handlers/flow.rb",
    "lib/handlers/fts.rb",
    "lib/handlers/getkey.rb",
    "lib/handlers/getlabel.rb",
    "lib/handlers/help.rb",
    "lib/handlers/list.rb",
    "lib/handlers/list_counters.rb",
    "lib/handlers/meters.rb",
    "lib/handlers/options.rb",
    "lib/handlers/query_alerts.rb",
    "lib/handlers/query_flow.rb",
    "lib/handlers/query_fts.rb",
    "lib/handlers/query_resource.rb",
    "lib/handlers/resolve.rb",
    "lib/handlers/resource.rb",
    "lib/handlers/set.rb",
    "lib/handlers/timeslices.rb",
    "lib/handlers/toppers.rb",
    "lib/handlers/trackers.rb",
    "lib/handlers/traffic.rb",
    "lib/itrp.rb",
    "test/helper.rb",
    "test/test_itrp.rb"
  ]
  s.homepage = "http://github.com/vivekrajan/itrp"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "iTRP - Command Line Interface to Trisul Network Analytics"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<trisulrp>, [">= 0"])
      s.add_runtime_dependency(%q<terminal-table>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<trisulrp>, [">= 0"])
      s.add_dependency(%q<terminal-table>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<trisulrp>, [">= 0"])
    s.add_dependency(%q<terminal-table>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

